# Generated by Django 3.1.7 on 2021-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210305_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='get_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
