# Generated by Django 3.1.7 on 2021-03-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_transaction_get_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.RemoveField(
            model_name='product',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
    ]
