# Generated by Django 3.1.7 on 2021-03-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210305_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='b_user',
        ),
    ]
